networks:
  itmo:

services:
  user-service:
    build:
      context: ./
      dockerfile: ./user-service/Dockerfile
    networks:
      - itmo
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: container-registry.oracle.com/database/free:latest
    environment:
      ORACLE_PWD: password
      ORACLE_SID: FREE
      ORACLE_CHARACTERSET: AL32UTF8
    networks:
      - itmo
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "sys/password@FREE as sysdba", "SELECT 1 FROM dual"]
      interval: 10s
      timeout: 5s
      retries: 20

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - itmo
    depends_on:
      - user-service